CREATE TABLE `investors` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`full_name` varchar(255) NOT NULL,
	`email` varchar(255) NOT NULL,
	`phone` varchar(20) NOT NULL,
	`date_of_birth` varchar(10),
	`address` text,
	`city` varchar(100),
	`state` varchar(100),
	`pincode` varchar(10),
	`investment_budget` decimal(15,2),
	`property_types` text,
	`preferred_locations` text,
	`investment_purpose` varchar(50),
	`pan_number` varchar(10),
	`aadhar_number` varchar(12),
	`occupation` varchar(100),
	`annual_income` varchar(50),
	`status` varchar(20) DEFAULT 'pending',
	`verification_status` varchar(20) DEFAULT 'unverified',
	`created_at` timestamp DEFAULT (now()),
	`updated_at` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `investors_id` PRIMARY KEY(`id`),
	CONSTRAINT `investors_email_unique` UNIQUE(`email`)
);
