import { db } from './client.js';
import { properties } from './schema.js';

// Helper function to generate slug from title
function generateSlug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

const sampleProperties = [
  // Industrial Properties
  {
    title: 'Modern Warehouse Facility',
    slug: generateSlug('Modern Warehouse Facility'),
    description: 'State-of-the-art warehouse with high ceilings, loading docks, and climate control. Perfect for distribution and logistics operations.',
    propertyType: 'industrial',
    status: 'available',
    addressLine1: '1234 Industrial Blvd',
    city: 'Dallas',
    state: 'TX',
    pincode: '75201',
    locality: 'Industrial District',
    price: 2500000,
    builtUpArea: 50000,
    isFeatured: true,
    isVerified: true,
    featuredImage: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800',
    images: JSON.stringify(['https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800']),
  },
  {
    title: 'Manufacturing Plant',
    slug: generateSlug('Manufacturing Plant'),
    description: 'Fully equipped manufacturing facility with heavy-duty power infrastructure, office space, and ample parking.',
    propertyType: 'industrial',
    status: 'available',
    addressLine1: '5678 Factory Road',
    city: 'Houston',
    state: 'TX',
    pincode: '77001',
    locality: 'East Houston',
    price: 4200000,
    builtUpArea: 85000,
    isFeatured: false,
    isVerified: true,
    featuredImage: 'https://images.unsplash.com/photo-1565610222536-ef125c59da2e?w=800',
    images: JSON.stringify(['https://images.unsplash.com/photo-1565610222536-ef125c59da2e?w=800']),
  },
  {
    title: 'Distribution Center',
    slug: generateSlug('Distribution Center'),
    description: 'Strategic location near major highways. Features multiple loading bays, office space, and 24/7 security.',
    propertyType: 'industrial',
    status: 'available',
    addressLine1: '910 Logistics Parkway',
    city: 'Fort Worth',
    state: 'TX',
    pincode: '76101',
    locality: 'Alliance',
    price: 3800000,
    builtUpArea: 75000,
    isFeatured: true,
    isVerified: true,
    featuredImage: 'https://images.unsplash.com/photo-1553413077-190dd305871c?w=800',
    images: JSON.stringify(['https://images.unsplash.com/photo-1553413077-190dd305871c?w=800']),
  },
  {
    title: 'Cold Storage Facility',
    slug: generateSlug('Cold Storage Facility'),
    description: 'Temperature-controlled warehouse ideal for food distribution and pharmaceutical storage.',
    propertyType: 'industrial',
    status: 'available',
    addressLine1: '1122 Cold Chain Drive',
    city: 'Austin',
    state: 'TX',
    pincode: '78701',
    locality: 'East Austin',
    price: 5500000,
    builtUpArea: 60000,
    isFeatured: false,
    isVerified: true,
    featuredImage: 'https://images.unsplash.com/photo-1494412574643-ff11b0a5c1c3?w=800',
    images: JSON.stringify(['https://images.unsplash.com/photo-1494412574643-ff11b0a5c1c3?w=800']),
  },

  // Residential Properties
  {
    title: 'Luxury Estate Home',
    slug: generateSlug('Luxury Estate Home'),
    description: 'Stunning 5-bedroom estate with pool, home theater, and panoramic views. Premium finishes throughout.',
    propertyType: 'residential',
    status: 'available',
    addressLine1: '456 Estate Lane',
    city: 'Plano',
    state: 'TX',
    pincode: '75024',
    locality: 'West Plano',
    price: 1850000,
    carpetArea: 6500,
    bedrooms: 5,
    bathrooms: 4,
    isFeatured: true,
    isVerified: true,
    featuredImage: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
    images: JSON.stringify(['https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800']),
    amenities: JSON.stringify(['Swimming Pool', 'Home Theater', 'Garden', 'Garage', 'Security']),
  },
  {
    title: 'Modern Family Home',
    slug: generateSlug('Modern Family Home'),
    description: 'Beautiful 4-bedroom home in excellent school district. Open floor plan with updated kitchen and large backyard.',
    propertyType: 'residential',
    status: 'available',
    addressLine1: '789 Family Street',
    city: 'Frisco',
    state: 'TX',
    pincode: '75034',
    locality: 'Central Frisco',
    price: 675000,
    carpetArea: 3200,
    bedrooms: 4,
    bathrooms: 3,
    isFeatured: true,
    isVerified: true,
    featuredImage: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
    images: JSON.stringify(['https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800']),
    amenities: JSON.stringify(['Backyard', 'Garage', 'Modern Kitchen', 'Security']),
  },
  {
    title: 'Charming Townhouse',
    slug: generateSlug('Charming Townhouse'),
    description: 'Contemporary 3-bedroom townhouse with garage. Low maintenance living in prime location.',
    propertyType: 'residential',
    status: 'available',
    addressLine1: '321 Townhouse Row',
    city: 'McKinney',
    state: 'TX',
    pincode: '75069',
    locality: 'Historic Downtown',
    price: 425000,
    carpetArea: 2100,
    bedrooms: 3,
    bathrooms: 2,
    isFeatured: false,
    isVerified: true,
    featuredImage: 'https://images.unsplash.com/photo-1572120360610-d971b9d7767c?w=800',
    images: JSON.stringify(['https://images.unsplash.com/photo-1572120360610-d971b9d7767c?w=800']),
    amenities: JSON.stringify(['Garage', 'Patio', 'Security']),
  },
  {
    title: 'Waterfront Villa',
    slug: generateSlug('Waterfront Villa'),
    description: 'Exclusive lakefront property with private dock, 6 bedrooms, and resort-style amenities.',
    propertyType: 'residential',
    status: 'available',
    addressLine1: '555 Lakefront Drive',
    city: 'Lake Travis',
    state: 'TX',
    pincode: '78732',
    locality: 'Lakeside',
    price: 3200000,
    carpetArea: 8500,
    bedrooms: 6,
    bathrooms: 5,
    isFeatured: true,
    isVerified: true,
    featuredImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
    images: JSON.stringify(['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800']),
    amenities: JSON.stringify(['Private Dock', 'Swimming Pool', 'Gym', 'Garden', 'Security']),
  },
  {
    title: 'Starter Home',
    slug: generateSlug('Starter Home'),
    description: 'Cozy 3-bedroom home perfect for first-time buyers. Recently renovated with new appliances.',
    propertyType: 'residential',
    status: 'available',
    addressLine1: '888 Starter Lane',
    city: 'Arlington',
    state: 'TX',
    pincode: '76010',
    locality: 'East Arlington',
    price: 285000,
    carpetArea: 1650,
    bedrooms: 3,
    bathrooms: 2,
    isFeatured: false,
    isVerified: true,
    featuredImage: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800',
    images: JSON.stringify(['https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800']),
    amenities: JSON.stringify(['Parking', 'Backyard', 'New Appliances']),
  },

  // Commercial Properties
  {
    title: 'Downtown Office Building',
    slug: generateSlug('Downtown Office Building'),
    description: 'Class A office space in prime downtown location. Modern amenities, parking garage, and excellent visibility.',
    propertyType: 'commercial',
    status: 'available',
    addressLine1: '100 Main Street',
    city: 'Dallas',
    state: 'TX',
    pincode: '75201',
    locality: 'Downtown',
    price: 8500000,
    builtUpArea: 45000,
    isFeatured: true,
    isVerified: true,
    featuredImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800',
    images: JSON.stringify(['https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800']),
    amenities: JSON.stringify(['Parking Garage', 'Elevator', 'Security', 'Conference Rooms']),
  },
  {
    title: 'Retail Shopping Center',
    slug: generateSlug('Retail Shopping Center'),
    description: 'High-traffic retail center with anchor tenants. Excellent investment opportunity with stable income.',
    propertyType: 'commercial',
    status: 'available',
    addressLine1: '200 Shopping Plaza',
    city: 'Plano',
    state: 'TX',
    pincode: '75024',
    locality: 'Legacy West',
    price: 6200000,
    builtUpArea: 32000,
    isFeatured: true,
    isVerified: true,
    featuredImage: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800',
    images: JSON.stringify(['https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800']),
    amenities: JSON.stringify(['Parking', 'Security', 'Food Court']),
  },
  {
    title: 'Medical Office Complex',
    slug: generateSlug('Medical Office Complex'),
    description: 'Purpose-built medical facility with multiple suites, ample parking, and modern infrastructure.',
    propertyType: 'commercial',
    status: 'available',
    addressLine1: '300 Medical Drive',
    city: 'Richardson',
    state: 'TX',
    pincode: '75080',
    locality: 'Medical District',
    price: 4800000,
    builtUpArea: 28000,
    isFeatured: false,
    isVerified: true,
    featuredImage: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800',
    images: JSON.stringify(['https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800']),
    amenities: JSON.stringify(['Parking', 'Elevator', 'Security', 'Medical Equipment']),
  },
  {
    title: 'Restaurant & Bar Space',
    slug: generateSlug('Restaurant & Bar Space'),
    description: 'Turnkey restaurant space in entertainment district. Fully equipped kitchen and bar.',
    propertyType: 'commercial',
    status: 'available',
    addressLine1: '400 Entertainment Blvd',
    city: 'Fort Worth',
    state: 'TX',
    pincode: '76102',
    locality: 'Sundance Square',
    price: 1250000,
    builtUpArea: 5500,
    isFeatured: false,
    isVerified: true,
    featuredImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
    images: JSON.stringify(['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800']),
    amenities: JSON.stringify(['Commercial Kitchen', 'Bar', 'Patio', 'Parking']),
  },
  {
    title: 'Tech Office Campus',
    slug: generateSlug('Tech Office Campus'),
    description: 'Modern office campus with collaborative spaces, cafeteria, and fitness center. Perfect for tech companies.',
    propertyType: 'commercial',
    status: 'available',
    addressLine1: '500 Tech Parkway',
    city: 'Austin',
    state: 'TX',
    pincode: '78701',
    locality: 'Tech District',
    price: 12500000,
    builtUpArea: 65000,
    isFeatured: true,
    isVerified: true,
    featuredImage: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
    images: JSON.stringify(['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800']),
    amenities: JSON.stringify(['Cafeteria', 'Gym', 'Parking', 'Conference Rooms', 'Collaborative Spaces']),
  },

  // Farm Land Properties
  {
    title: 'Premium Cattle Ranch',
    slug: generateSlug('Premium Cattle Ranch'),
    description: '500-acre working cattle ranch with modern facilities, water rights, and excellent grazing land.',
    propertyType: 'farmland',
    status: 'available',
    addressLine1: 'Ranch Road 500',
    city: 'Waco',
    state: 'TX',
    pincode: '76701',
    locality: 'Rural Waco',
    price: 4500000,
    plotArea: 21780000, // 500 acres in sq ft
    areaUnit: 'acres',
    isFeatured: true,
    isVerified: true,
    featuredImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800',
    images: JSON.stringify(['https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800']),
    amenities: JSON.stringify(['Water Rights', 'Barn', 'Fencing', 'Grazing Land']),
  },
  {
    title: 'Organic Farm Land',
    slug: generateSlug('Organic Farm Land'),
    description: '200 acres of certified organic farmland with irrigation system and equipment barn.',
    propertyType: 'farmland',
    status: 'available',
    addressLine1: 'Farm Road 200',
    city: 'Tyler',
    state: 'TX',
    pincode: '75701',
    locality: 'Rural Tyler',
    price: 1800000,
    plotArea: 8712000, // 200 acres in sq ft
    areaUnit: 'acres',
    isFeatured: true,
    isVerified: true,
    featuredImage: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800',
    images: JSON.stringify(['https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800']),
    amenities: JSON.stringify(['Irrigation System', 'Equipment Barn', 'Organic Certification']),
  },
  {
    title: 'Vineyard Estate',
    slug: generateSlug('Vineyard Estate'),
    description: '150-acre vineyard with established vines, winery facility, and tasting room.',
    propertyType: 'farmland',
    status: 'available',
    addressLine1: 'Vineyard Lane 150',
    city: 'Fredericksburg',
    state: 'TX',
    pincode: '78624',
    locality: 'Wine Country',
    price: 5200000,
    plotArea: 6534000, // 150 acres in sq ft
    areaUnit: 'acres',
    isFeatured: true,
    isVerified: true,
    featuredImage: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800',
    images: JSON.stringify(['https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800']),
    amenities: JSON.stringify(['Winery', 'Tasting Room', 'Established Vines', 'Processing Facility']),
  },
  {
    title: 'Hay Production Farm',
    slug: generateSlug('Hay Production Farm'),
    description: '300 acres ideal for hay production. Includes equipment storage and good road access.',
    propertyType: 'farmland',
    status: 'available',
    addressLine1: 'County Road 300',
    city: 'Stephenville',
    state: 'TX',
    pincode: '76401',
    locality: 'Rural Stephenville',
    price: 2100000,
    plotArea: 13068000, // 300 acres in sq ft
    areaUnit: 'acres',
    isFeatured: false,
    isVerified: true,
    featuredImage: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=800',
    images: JSON.stringify(['https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=800']),
    amenities: JSON.stringify(['Equipment Storage', 'Road Access', 'Irrigation']),
  },
  {
    title: 'Pecan Orchard',
    slug: generateSlug('Pecan Orchard'),
    description: '100-acre mature pecan orchard with irrigation and processing facility.',
    propertyType: 'farmland',
    status: 'available',
    addressLine1: 'Pecan Grove Road',
    city: 'San Saba',
    state: 'TX',
    pincode: '76877',
    locality: 'Pecan Capital',
    price: 2800000,
    plotArea: 4356000, // 100 acres in sq ft
    areaUnit: 'acres',
    isFeatured: false,
    isVerified: true,
    featuredImage: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800',
    images: JSON.stringify(['https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800']),
    amenities: JSON.stringify(['Mature Trees', 'Irrigation', 'Processing Facility']),
  },

  // Rental Properties (using apartment type with rental status)
  {
    title: 'Luxury Downtown Apartment',
    slug: generateSlug('Luxury Downtown Apartment'),
    description: 'High-rise 2-bedroom apartment with stunning city views, gym, and concierge service.',
    propertyType: 'rental',
    status: 'available',
    addressLine1: '600 Downtown Tower',
    city: 'Dallas',
    state: 'TX',
    pincode: '75201',
    locality: 'Downtown',
    price: 3200, // Monthly rent
    carpetArea: 1400,
    bedrooms: 2,
    bathrooms: 2,
    isFeatured: true,
    isVerified: true,
    featuredImage: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    images: JSON.stringify(['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800']),
    amenities: JSON.stringify(['Gym', 'Concierge', 'City Views', 'Parking']),
  },
  {
    title: 'Family Home for Rent',
    slug: generateSlug('Family Home for Rent'),
    description: 'Spacious 4-bedroom home with backyard, garage, and great school district.',
    propertyType: 'rental',
    status: 'available',
    addressLine1: '700 Family Circle',
    city: 'Frisco',
    state: 'TX',
    pincode: '75034',
    locality: 'Frisco ISD',
    price: 2800, // Monthly rent
    carpetArea: 2800,
    bedrooms: 4,
    bathrooms: 3,
    isFeatured: true,
    isVerified: true,
    featuredImage: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    images: JSON.stringify(['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800']),
    amenities: JSON.stringify(['Backyard', 'Garage', 'School District']),
  },
  {
    title: 'Modern Studio Apartment',
    slug: generateSlug('Modern Studio Apartment'),
    description: 'Stylish studio in trendy neighborhood. Walking distance to restaurants and shops.',
    propertyType: 'rental',
    status: 'available',
    addressLine1: '800 Studio Lane',
    city: 'Austin',
    state: 'TX',
    pincode: '78701',
    locality: 'Downtown Austin',
    price: 1450, // Monthly rent
    carpetArea: 650,
    bedrooms: 0, // Studio
    bathrooms: 1,
    isFeatured: false,
    isVerified: true,
    featuredImage: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    images: JSON.stringify(['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800']),
    amenities: JSON.stringify(['Modern Finishes', 'Walkable', 'Parking']),
  },
  {
    title: 'Townhouse Rental',
    slug: generateSlug('Townhouse Rental'),
    description: '3-bedroom townhouse with attached garage and private patio. Pet-friendly.',
    propertyType: 'rental',
    status: 'available',
    addressLine1: '900 Townhouse Way',
    city: 'Plano',
    state: 'TX',
    pincode: '75024',
    locality: 'West Plano',
    price: 2200, // Monthly rent
    carpetArea: 1900,
    bedrooms: 3,
    bathrooms: 2,
    isFeatured: false,
    isVerified: true,
    featuredImage: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
    images: JSON.stringify(['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800']),
    amenities: JSON.stringify(['Garage', 'Patio', 'Pet Friendly']),
  },
  {
    title: 'Commercial Office Space',
    slug: generateSlug('Commercial Office Space'),
    description: 'Professional office space for rent. Includes utilities, parking, and conference room access.',
    propertyType: 'commercial',
    status: 'available',
    addressLine1: '1000 Office Park',
    city: 'Richardson',
    state: 'TX',
    pincode: '75080',
    locality: 'Telecom Corridor',
    price: 4500, // Monthly rent
    builtUpArea: 2500,
    isFeatured: false,
    isVerified: true,
    featuredImage: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800',
    images: JSON.stringify(['https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800']),
    amenities: JSON.stringify(['Utilities Included', 'Parking', 'Conference Room']),
  },
  {
    title: 'Lakefront Condo',
    slug: generateSlug('Lakefront Condo'),
    description: 'Beautiful 3-bedroom condo with lake views, pool, and boat dock access.',
    propertyType: 'rental',
    status: 'available',
    addressLine1: '1100 Lakeside Drive',
    city: 'Lake Lewisville',
    state: 'TX',
    pincode: '75057',
    locality: 'Lakefront',
    price: 3800, // Monthly rent
    carpetArea: 2100,
    bedrooms: 3,
    bathrooms: 2,
    isFeatured: true,
    isVerified: true,
    featuredImage: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800',
    images: JSON.stringify(['https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800']),
    amenities: JSON.stringify(['Lake Views', 'Pool', 'Boat Dock', 'Security']),
  },
];

async function seedProperties() {
  try {
    console.log('🌱 Starting property seeding...');

    // Insert all properties
    for (const property of sampleProperties) {
      // Convert numeric fields to strings for decimal columns
      const propertyData = {
        ...property,
        price: property.price.toString(),
        builtUpArea: property.builtUpArea?.toString(),
        carpetArea: property.carpetArea?.toString(),
        plotArea: property.plotArea?.toString(),
      };
      await db.insert(properties).values(propertyData);
      console.log(`✅ Added: ${property.title} (${property.propertyType})`);
    }

    console.log(`\n✨ Successfully seeded ${sampleProperties.length} properties!`);
    console.log('\nBreakdown by type:');
    console.log(`- Industrial: ${sampleProperties.filter((p) => p.propertyType === 'industrial').length}`);
    console.log(`- Residential (Villa): ${sampleProperties.filter((p) => p.propertyType === 'villa').length}`);
    console.log(`- Residential (Apartment): ${sampleProperties.filter((p) => p.propertyType === 'apartment').length}`);
    console.log(`- Commercial: ${sampleProperties.filter((p) => p.propertyType === 'commercial').length}`);
    console.log(`- Farm Land: ${sampleProperties.filter((p) => p.propertyType === 'farmhouse').length}`);
  } catch (error) {
    console.error('❌ Error seeding properties:', error);
    throw error;
  }
}

// Run the seed function
seedProperties()
  .then(() => {
    console.log('\n🎉 Seeding complete!');
    process.exit(0);
  })
  .catch((error) => {
    console.error('Failed to seed properties:', error);
    process.exit(1);
  });
